server:
  port: 8888
spring:  application:    name: config-server
  cloud:    config:      server:        git:          uri: https://github.com/notoriouscode/stock-config
          default-label: main
          username: notoriouscode
          password: Satyam@@32@@
          clone-on-start: true